spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/snipit_db

  jpa:
    hibernate:
      ddl-auto: update

